# Generated by Django 3.0.8 on 2020-07-26 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('cert_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('num_signs', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('dimensions', models.TextField()),
                ('tags', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
