# Generated by Django 3.0.8 on 2020-07-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='font',
            fields=[
                ('font_id', models.AutoField(primary_key=True, serialize=False)),
                ('font_name', models.CharField(max_length=50)),
                ('font', models.FileField(blank=True, null=True, upload_to='fonts')),
            ],
        ),
    ]
