# Generated by Django 2.1.3 on 2020-07-30 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_font'),
    ]

    operations = [
        migrations.RenameField(
            model_name='font',
            old_name='font',
            new_name='font_file',
        ),
    ]
