# Generated by Django 3.0.8 on 2020-07-30 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_auto_20200730_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='font_used',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='certificates.font'),
        ),
    ]
