# Generated by Django 3.0.8 on 2020-07-30 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_remove_certificate_font_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='font_used',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='certificates.font'),
        ),
    ]
