# Generated by Django 3.0.8 on 2020-07-31 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_certificate_font_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='font_size1',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(72)]),
        ),
        migrations.AddField(
            model_name='certificate',
            name='font_size2',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(72)]),
        ),
    ]
