# Generated by Django 3.0.8 on 2020-07-31 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0009_auto_20200731_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='num_signs',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
