# Generated by Django 3.0.7 on 2020-08-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0010_auto_20200731_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='certificate',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_templates'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_templates'),
        ),
    ]
