# Generated by Django 3.0.7 on 2020-08-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0012_auto_20200808_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='image',
            new_name='image1',
        ),
    ]
